[formatter.md]
command = "prettier"
options = ["--prose-wrap", "always", "--print-width", "120", "--write"]
includes = ["*.md"]

[formatter.nix]
command = "alejandra"
includes = ["*.nix"]

[formatter.toml]
command = "taplo"
options = ["format"]
includes = ["*.toml"]
excludes = ["crates/my-workspace-hack/Cargo.toml"]
