
[commands]
lint = ["cargo", "clippy", "--all-targets", "--", "--deny", "warnings"]
test = ["cargo", "nextest", "run", "--no-fail-fast"]
build = ["cargo", "build"]
format = ["cargo", "fmt"]

[[checks]]
name = "check"
command = ["cargo", "check"]

[[checks]]
name = "semgrep"
command = ["semgrep", "scan", "--config=./.config/semgrep_rules.yaml", "--strict"]
